"""
Game map (isometric diorama image) -> layered 3D scene for three.js.

Stages:
  1. geometry  MoGe-3 point map + camera from the single image (MIT, Microsoft).
  2. frame     RANSAC ground plane -> right-handed map frame (x, y up, z), aligned to the diorama's edges.
  3. segment   SAM 2.1 automatic masks on overlapping tiles (small props) + one full-image pass (big cliffs).
  4. classify  masks -> tree / rock / cliff / water / decal by height above ground + color; tall pixels no mask
               claimed become cliffs.
  5. terrain   ground-level samples only -> top-down heightmap + albedo (image projected, so paths stay sharp).
  6. props     RGBA crop per object; similar trees/rocks share a few variants; placement from the point map.
               Variants are generated by the Hunyuan3D worker (callback), then instanced.
  7. compose   GLB scene: Terrain, Water, Props/<variant> instances, Collision (hidden, low-res heightfield).

Units: 1 = MAP_SIZE metres across the longer edge of the map; y up; scene centred on the terrain.
"""
import colorsys
import gc
import sys
from dataclasses import dataclass, field
from io import BytesIO
from typing import Callable, Optional

import numpy as np
import torch
import trimesh
from PIL import Image
from scipy import ndimage
from scipy.cluster.vq import kmeans2

GRID = 512  # heightmap cells along the longer edge
COLLISION_GRID = 128
MAP_SIZE = 100.0  # metres
WATER_DEPTH = 0.004  # terrain carved under water (map units) so the water surface reads
MOGE_MODEL = "Ruicheng/moge-3-vitg"
SAM_MODEL = "facebook/sam2.1-hiera-large"


@dataclass(eq=False)
class Frame:
    points: np.ndarray  # (H, W, 3) camera space
    valid: np.ndarray  # (H, W) pixel belongs to the diorama
    height: np.ndarray  # (H, W) height above ground (camera units), nan outside
    thr: float  # plane fit tolerance (camera units)
    c0: np.ndarray
    u: np.ndarray
    n: np.ndarray
    v: np.ndarray
    R: np.ndarray
    lo: np.ndarray
    size: float
    extent: np.ndarray  # (2,) map extent in map units (x, z), longer edge = 1

    def to_map(self, p: np.ndarray) -> np.ndarray:
        """Camera-space points -> map frame (x, y up, z), origin at the map's min corner on the ground."""
        q = p - self.c0
        xz = np.stack([q @ self.u, q @ self.v], -1) @ self.R
        return np.stack([(xz[..., 0] - self.lo[0]) / self.size, (q @ self.n) / self.size, (xz[..., 1] - self.lo[1]) / self.size], -1)


@dataclass(eq=False)
class Prop:
    kind: str
    mask: np.ndarray = field(repr=False)
    area: int
    box: tuple
    color: np.ndarray = field(default=None, repr=False)
    pos: tuple = (0.0, 0.0, 0.0)
    height: float = 0.0
    width: float = 0.0
    variant: str = ""


# ---------------- 1. geometry ----------------
def _moge(device: str):
    if not device.startswith("cuda"):
        # The MoGe-3 refiner (sparse 3D UNet) needs CUDA flex_gemm; elsewhere load without it.
        import types

        class _Unavailable:
            def __init__(self, *a, **k):
                raise RuntimeError("flex_gemm needs CUDA")

        stub = types.ModuleType("flex_gemm")
        stub.nn = types.ModuleType("flex_gemm.nn")
        stub.ops = types.ModuleType("flex_gemm.ops")
        stub.nn.SubmanifoldConv3d = stub.nn.SparsePool3d = stub.nn.SparseUpsample3d = _Unavailable
        stub.ops.NeighborCache = _Unavailable
        sys.modules.setdefault("flex_gemm", stub)
        sys.modules.setdefault("flex_gemm.nn", stub.nn)
        sys.modules.setdefault("flex_gemm.ops", stub.ops)
    from moge.model.v3 import MoGeModel

    kwargs = None if device.startswith("cuda") else {"refiner": None}
    return MoGeModel.from_pretrained(MOGE_MODEL, model_kwargs=kwargs).to(device).eval()


def estimate_geometry(img: np.ndarray, device: str) -> tuple[np.ndarray, np.ndarray]:
    model = _moge(device)
    x = torch.tensor(img / 255, dtype=torch.float32, device=device).permute(2, 0, 1)
    with torch.no_grad():
        out = model.infer(x, refine_steps=3 if device.startswith("cuda") else 0)
    points, mask = out["points"].float().cpu().numpy(), out["mask"].cpu().numpy().astype(bool)
    del model, out
    free_memory()
    return points, mask


# ---------------- 2. frame ----------------
def build_frame(img: np.ndarray, points: np.ndarray, mask: np.ndarray) -> Frame:
    H, W = points.shape[:2]
    valid = np.isfinite(points).all(-1) & mask
    bg = img[:8, :8].reshape(-1, 3).mean(0)  # flat backdrop around the diorama
    valid &= np.abs(img.astype(float) - bg).sum(-1) > 40
    P = points[valid].astype(np.float64)
    rng = np.random.default_rng(0)
    S = P[rng.choice(len(P), min(len(P), 50000), replace=False)]

    # RANSAC dominant plane = playable ground.
    scale = np.median(np.linalg.norm(S - np.median(S, 0), axis=1))
    thr = scale * 0.01
    best, plane = 0, None
    for _ in range(400):
        a, b, c = S[rng.choice(len(S), 3, replace=False)]
        n = np.cross(b - a, c - a)
        if np.linalg.norm(n) < 1e-12:
            continue
        n /= np.linalg.norm(n)
        k = int((np.abs((S - a) @ n) < thr).sum())
        if k > best:
            best, plane = k, (n, a)
    n, a = plane
    Q = P[np.abs((P - a) @ n) < thr]
    c0 = Q.mean(0)
    n = np.linalg.svd(Q - c0, full_matrices=False)[2][-1]
    if n @ (-c0) < 0:  # camera (origin) is above the ground
        n = -n
    ref = np.array([1.0, 0, 0])
    u = ref - (ref @ n) * n
    u /= np.linalg.norm(u)
    v = np.cross(u, n)  # right-handed: x=u, y=n, z=v

    q = P - c0
    h = q @ n
    xz = np.stack([q @ u, q @ v], -1)
    ground = np.abs(h) < thr * 3
    # Rotate so the diorama's edges follow the grid: minimum-area rectangle of the ground footprint.
    g = xz[ground][::10]
    angles = np.linspace(0, np.pi / 2, 180)
    areas = [np.ptp(g @ [np.cos(t), np.sin(t)]) * np.ptp(g @ [-np.sin(t), np.cos(t)]) for t in angles]
    t = angles[int(np.argmin(areas))]
    R = np.array([[np.cos(t), -np.sin(t)], [np.sin(t), np.cos(t)]])
    gxz = xz[ground] @ R
    lo, hi = np.percentile(gxz, 0.2, 0), np.percentile(gxz, 99.8, 0)
    size = float((hi - lo).max())

    height = np.full((H, W), np.nan)
    height[valid] = h
    return Frame(points, valid, height, float(thr), c0, u, n, v, R, lo, size, (hi - lo) / size)


# ---------------- 3. segment ----------------
def segment(img: Image.Image, device: str) -> np.ndarray:
    from transformers import pipeline

    gen = pipeline("mask-generation", model=SAM_MODEL, device=device)
    W, H = img.size
    TILE, STEP = 480, 360  # SAM upsamples each tile to 1024 px, so small props get enough pixels
    masks, scores = [], []

    def add(out, x, y, keep):
        for m, sc in zip(out["masks"], out["scores"]):
            m = np.asarray(m, bool)
            if not keep(m):
                continue
            full = np.zeros((H, W), bool)
            full[y : y + m.shape[0], x : x + m.shape[1]] = m
            masks.append(full)
            scores.append(float(sc))

    kw = dict(points_per_batch=64, points_per_crop=32, pred_iou_thresh=0.8, stability_score_thresh=0.9)
    ys = sorted(set(list(range(0, max(1, H - TILE), STEP)) + [max(0, H - TILE)]))
    xs = sorted(set(list(range(0, max(1, W - TILE), STEP)) + [max(0, W - TILE)]))
    for y in ys:
        for x in xs:
            # Masks touching an inner tile edge are cut objects; the neighbouring tile sees them whole.
            def keep(m, x=x, y=y):
                cut = (m[0].any() and y > 0) or (m[-1].any() and y + TILE < H) or (m[:, 0].any() and x > 0) or (m[:, -1].any() and x + TILE < W)
                return not cut and m.sum() >= 30

            add(gen(img.crop((x, y, x + TILE, y + TILE)), **kw), x, y, keep)
    add(gen(img, **kw), 0, 0, lambda m: m.sum() > 4000)  # big objects the tiles cut

    keep = []
    for i in np.argsort(scores)[::-1]:  # overlaps between tiles: IoU > 0.6 = same mask
        if all((masks[i] & masks[j]).sum() / (masks[i] | masks[j]).sum() < 0.6 for j in keep):
            keep.append(i)
    del gen
    free_memory()
    return np.array([masks[i] for i in keep]) if keep else np.zeros((0, H, W), bool)


# ---------------- 4. classify ----------------
def _hsv(rgb):
    return colorsys.rgb_to_hsv(*(np.asarray(rgb) / 255))


def classify(img: np.ndarray, frame: Frame, masks: np.ndarray) -> tuple[list[Prop], np.ndarray]:
    """Props (tree / rock / cliff) and the water mask."""
    H, W = img.shape[:2]
    obj_h = frame.thr * 8
    props, water = [], np.zeros((H, W), bool)
    for m in masks:
        area = int(m.sum())
        h = frame.height[m]
        h = h[np.isfinite(h)]
        if area > 0.25 * H * W or len(h) < 0.5 * area:  # whole-map or backdrop masks
            continue
        col = img[m].mean(0)
        hue, sat, _ = _hsv(col)
        blue = 0.45 < hue < 0.6 and sat > 0.3
        if np.percentile(h, 90) < obj_h:
            if blue:
                water |= m
            continue  # flat decals (paths, stones) stay in the terrain texture
        if blue:
            continue  # water on a ledge (waterfall top)
        if area > 6000:
            kind = "cliff"
        elif sat > 0.25 and area < 3000 and ((col[1] > col[0] * 1.05 and col[1] > col[2]) or 0.05 < hue < 0.14):
            kind = "tree"  # green pines and warm autumn foliage
        else:
            kind = "rock"
        props.append(Prop(kind, m, area, _box(m), col))

    # Tall pixels no mask claimed (cliff walls SAM split into facets) -> connected components = cliffs.
    covered = np.zeros((H, W), bool)
    for p in props:
        covered |= p.mask
    tall = np.nan_to_num(frame.height, nan=-1) > obj_h * 2
    lab, nlab = ndimage.label(ndimage.binary_opening(tall & ~covered, iterations=2))
    for k in range(1, nlab + 1):
        m = lab == k
        if m.sum() >= 1500:
            props.append(Prop("cliff", m, int(m.sum()), _box(m), img[m].mean(0)))

    # One object split into overlapping masks: keep the larger.
    props.sort(key=lambda p: -p.area)
    kept = []
    for p in props:
        if all((p.mask & k.mask).sum() < 0.5 * p.area for k in kept):
            kept.append(p)
    return kept, water


def _box(m):
    ys, xs = np.nonzero(m)
    return int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())


# ---------------- 5. terrain ----------------
def build_terrain(img: np.ndarray, frame: Frame, water: np.ndarray):
    """Heightmap (map units), albedo image and water cell mask on a GZ x GX grid."""
    GX, GZ = [max(2, int(round((GRID - 1) * e)) + 1) for e in frame.extent]
    P = frame.to_map(frame.points[frame.valid].astype(np.float64))
    C = img[frame.valid]
    W_ = water[frame.valid]
    gx = np.round(P[:, 0] * (GRID - 1)).astype(int)
    gz = np.round(P[:, 2] * (GRID - 1)).astype(int)
    ground = P[:, 1] <= frame.thr * 8 / frame.size  # anything higher is a prop
    ok = (gx >= 0) & (gx < GX) & (gz >= 0) & (gz < GZ) & ground
    gx, gz, h, col, wat = gx[ok], gz[ok], P[ok, 1], C[ok], W_[ok]

    height = np.full((GZ, GX), -np.inf)
    np.maximum.at(height, (gz, gx), h)
    top = h >= height[gz, gx] - frame.thr / frame.size
    albedo = np.zeros((GZ, GX, 3))
    cnt = np.zeros((GZ, GX))
    np.add.at(albedo, (gz[top], gx[top]), col[top])
    np.add.at(cnt, (gz[top], gx[top]), 1)
    water_cells = np.zeros((GZ, GX))
    np.add.at(water_cells, (gz, gx), wat)
    seen = cnt > 0
    albedo[seen] /= cnt[seen, None]

    # Holes (under props, occluded): nearest seed, then diffuse so they blend instead of streaking.
    idx = ndimage.distance_transform_edt(~seen, return_distances=False, return_indices=True)
    height = np.where(seen, height, height[tuple(idx)])
    albedo = albedo[tuple(idx)]
    for _ in range(200):
        height = np.where(seen, height, ndimage.uniform_filter(height, 5))
        albedo = np.where(seen[..., None], albedo, ndimage.uniform_filter(albedo, (5, 5, 1)))
    height = ndimage.median_filter(height, 3)
    water_cells = ndimage.binary_closing(water_cells > 0, iterations=2)
    water_cells = ndimage.binary_opening(water_cells, iterations=1)
    return height, albedo.clip(0, 255).astype(np.uint8), water_cells


# ---------------- 6. props ----------------
def place_props(img: np.ndarray, frame: Frame, props: list[Prop]) -> dict[str, Image.Image]:
    """Fill placement per prop, assign variants; returns variant -> RGBA crop for the 3D generator."""
    H, W = img.shape[:2]
    for p in props:
        m = p.mask & frame.valid
        P = frame.to_map(frame.points[m].astype(np.float64))
        base = P[P[:, 1] < np.percentile(P[:, 1], 15)]  # the object's foot
        p.pos = (float(base[:, 0].mean()), float(np.median(base[:, 1])), float(base[:, 2].mean()))
        p.height = float(np.percentile(P[:, 1], 98) - p.pos[1])
        p.width = float(np.ptp(P[:, [0, 2]], 0).max())

    for kind, kmax in (("tree", 3), ("rock", 3)):  # instances share a few generated variants
        group = [p for p in props if p.kind == kind]
        if not group:
            continue
        k = min(kmax, len(group))
        _, lab = kmeans2(np.array([p.color for p in group], float), k, seed=0, minit="++")
        for c in range(k):
            members = [p for p, l in zip(group, lab) if l == c]
            if members:
                rep = max(members, key=lambda p: p.area)  # biggest = least occluded
                for p in members:
                    p.variant = f"{kind}_{props.index(rep)}"
    crops = {}
    for i, p in enumerate(props):
        p.variant = p.variant or f"{p.kind}_{i}"
        if p.variant == f"{p.kind}_{i}":
            x0, y0, x1, y1 = p.box
            pad = int(0.15 * max(x1 - x0, y1 - y0)) + 4
            x0, y0, x1, y1 = max(0, x0 - pad), max(0, y0 - pad), min(W, x1 + pad), min(H, y1 + pad)
            rgba = np.dstack([img[y0:y1, x0:x1], (p.mask[y0:y1, x0:x1] * 255).astype(np.uint8)])
            crops[p.variant] = Image.fromarray(rgba, "RGBA")
    return crops


# ---------------- 7. compose ----------------
def _grid_mesh(height: np.ndarray, scale: float, cells: Optional[np.ndarray] = None, y: Optional[float] = None):
    GZ, GX = height.shape
    zs, xs = np.mgrid[0:GZ, 0:GX]
    verts = np.stack([xs / (GRID - 1) * scale, (height if y is None else np.full_like(height, y)), zs / (GRID - 1) * scale], -1).reshape(-1, 3)
    i = (zs[:-1, :-1] * GX + xs[:-1, :-1])
    quad = np.ones_like(i, bool) if cells is None else cells[:-1, :-1] & cells[1:, 1:] & cells[1:, :-1] & cells[:-1, 1:]
    i = i[quad].ravel()
    faces = np.concatenate([np.stack([i, i + GX, i + 1], 1), np.stack([i + 1, i + GX, i + GX + 1], 1)])
    uv = np.stack([xs / (GX - 1), 1 - zs / (GZ - 1)], -1).reshape(-1, 2)
    return verts, faces, uv


def compose(frame: Frame, height: np.ndarray, albedo: np.ndarray, water: np.ndarray, props: list[Prop],
            variant_glbs: dict[str, bytes], yaw_offset: float = 0.0) -> tuple[bytes, dict]:
    S = MAP_SIZE
    height = height.copy()
    wl = float(np.median(height[water])) if water.any() else None
    if wl is not None:  # carve under water so the surface sits above the bed
        height[water] = np.minimum(height[water], wl - WATER_DEPTH)
    scene = trimesh.Scene()

    verts, faces, uv = _grid_mesh(height * S, S)
    mat = trimesh.visual.material.PBRMaterial(name="Terrain", baseColorTexture=Image.fromarray(albedo), metallicFactor=0.0, roughnessFactor=1.0)
    terrain = trimesh.Trimesh(verts, faces, visual=trimesh.visual.TextureVisuals(uv=uv, material=mat), process=False)
    scene.add_geometry(terrain, node_name="Terrain", geom_name="Terrain")

    if wl is not None:
        wv, wf, _ = _grid_mesh(height * S, S, cells=ndimage.binary_dilation(water, iterations=2), y=(wl + WATER_DEPTH * 0.25) * S)
        if len(wf):
            wmat = trimesh.visual.material.PBRMaterial(name="Water", baseColorFactor=[0.25, 0.62, 0.82, 0.78], alphaMode="BLEND", metallicFactor=0.0, roughnessFactor=0.1)
            wm = trimesh.Trimesh(wv, wf, process=True)
            wm.remove_unreferenced_vertices()
            wm.visual = trimesh.visual.TextureVisuals(material=wmat)
            scene.add_geometry(wm, node_name="Water", geom_name="Water")

    # Camera direction on the map: every prop turns its generated front (the side seen in the image) toward it.
    cam = frame.to_map(np.zeros(3)) - frame.to_map(frame.c0)
    yaw = float(np.arctan2(cam[0], cam[2])) + yaw_offset
    counts: dict[str, int] = {}
    for p in props:
        data = variant_glbs.get(p.variant)
        if not data:
            continue
        base = _load_variant(data, p.variant)
        if base is None:
            continue
        lo_, hi_ = base.bounds
        # Fit the visible height and the footprint; the smaller scale keeps the generated shape (whose
        # proportions are guessed for the hidden sides) from overhanging its neighbours.
        s = min(p.height * S / max(hi_[1] - lo_[1], 1e-6), p.width * S / max(hi_[0] - lo_[0], hi_[2] - lo_[2], 1e-6))
        T = trimesh.transformations.rotation_matrix(yaw, [0, 1, 0])
        T[:3, :3] *= s
        foot = np.array([(lo_[0] + hi_[0]) / 2, lo_[1], (lo_[2] + hi_[2]) / 2])
        T[:3, 3] = np.array(p.pos) * S - T[:3, :3] @ foot
        name = f"Props/{p.variant}"
        n = counts.get(p.variant, 0)
        scene.add_geometry(base, node_name=f"{name}#{n}", geom_name=name, transform=T)  # same geometry = instanced
        counts[p.variant] = n + 1

    cv, cf, _ = _grid_mesh(ndimage.zoom(height, COLLISION_GRID / max(height.shape), order=1) * S, S * (GRID - 1) / (COLLISION_GRID - 1))
    collision = trimesh.Trimesh(cv, cf, process=False)
    collision.visual = trimesh.visual.TextureVisuals(material=trimesh.visual.material.PBRMaterial(name="Collision", baseColorFactor=[1, 0, 1, 0.3], alphaMode="BLEND"))
    scene.add_geometry(collision, node_name="Collision", geom_name="Collision")

    # Centre the map on the origin, ground at y=0.
    c = np.array([frame.extent[0] * S / 2, 0.0, frame.extent[1] * S / 2])
    scene.apply_transform(trimesh.transformations.translation_matrix(-c))
    buf = BytesIO()
    scene.export(buf, file_type="glb")
    stats = {"props": sum(counts.values()), "variants": len(counts), "water": int(bool(wl is not None)),
             "terrain_faces": int(len(faces)), "size_m": S}
    return buf.getvalue(), stats


def _load_variant(data: bytes, name: str) -> Optional[trimesh.Trimesh]:
    try:
        mesh = trimesh.load(BytesIO(data), file_type="glb", force="mesh")
    except Exception:
        return None
    if not isinstance(mesh, trimesh.Trimesh) or not len(mesh.faces):
        return None
    mesh.metadata["name"] = name
    return mesh


def free_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    elif torch.backends.mps.is_available():
        torch.mps.empty_cache()


# ---------------- driver ----------------
def run(image: Image.Image, device: str, generate_variants: Callable[[dict[str, Image.Image]], dict[str, bytes]],
        on_stage: Callable[[str], None] = lambda s: None) -> tuple[bytes, dict]:
    image = image.convert("RGB")
    image.thumbnail((1600, 1600))
    img = np.asarray(image)
    on_stage("Estimating depth")
    points, mask = estimate_geometry(img, device)
    frame = build_frame(img, points, mask)
    on_stage("Finding objects")
    masks = segment(image, device)
    props, water_px = classify(img, frame, masks)
    on_stage("Building terrain")
    height, albedo, water = build_terrain(img, frame, water_px)
    crops = place_props(img, frame, props)
    on_stage("Generating props")
    glbs = generate_variants(crops)
    on_stage("Composing scene")
    return compose(frame, height, albedo, water, props, glbs)
