"""
Map worker for Forma3D: game map image (isometric diorama) -> layered GLB scene (see mapgen.py).
Separate from the single-object Hunyuan3D worker; props are generated by that worker over HTTP.

API (all routes except /healthz and /v1/crops require `Authorization: Bearer $WORKER_TOKEN`):
  POST /v1/jobs            {image_url}
  GET  /v1/jobs/{id}       -> {id, status: queued|running|completed|failed, stage, progress, queue_position, error, timings, stats}
  GET  /v1/jobs/{id}/model -> model/gltf-binary
  GET  /v1/crops/{job}/{variant}.png  prop crops fetched by the Hunyuan3D worker (job ids are random 128-bit)
  GET  /healthz
"""
import os

DATA_ROOT = os.path.abspath(os.environ.get("DATA_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "data")))
os.environ.setdefault("HF_HOME", os.path.join(DATA_ROOT, "models"))

import hmac  # noqa: E402
import ipaddress  # noqa: E402
import logging  # noqa: E402
import queue  # noqa: E402
import re  # noqa: E402
import shutil  # noqa: E402
import socket  # noqa: E402
import threading  # noqa: E402
import time  # noqa: E402
import traceback  # noqa: E402
import uuid  # noqa: E402
from dataclasses import dataclass, field  # noqa: E402
from io import BytesIO  # noqa: E402
from typing import Optional  # noqa: E402
from urllib.parse import urlparse  # noqa: E402

import requests  # noqa: E402
import torch  # noqa: E402
import uvicorn  # noqa: E402
from fastapi import Depends, FastAPI, Header, HTTPException  # noqa: E402
from fastapi.responses import FileResponse  # noqa: E402
from PIL import Image  # noqa: E402
from pydantic import BaseModel  # noqa: E402

import mapgen  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("map-worker")

TOKEN = os.environ.get("WORKER_TOKEN", "")
if len(TOKEN) < 24:
    raise SystemExit("WORKER_TOKEN must be set (>= 24 chars)")
DEVICE = os.environ.get("DEVICE") or ("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
PORT = int(os.environ.get("PORT", "8083"))
# URL the Hunyuan3D worker uses to fetch prop crops from this worker.
PUBLIC_URL = os.environ.get("PUBLIC_URL", f"http://localhost:{PORT}").rstrip("/")
HUNYUAN_URL = os.environ.get("HUNYUAN_WORKER_URL", "http://localhost:8081").rstrip("/")
HUNYUAN_TOKEN = os.environ.get("HUNYUAN_WORKER_TOKEN", TOKEN)
DATA_DIR = os.environ.get("DATA_DIR", os.path.join(DATA_ROOT, "map-jobs"))
ALLOWED_IMAGE_HOSTS = {h for h in os.environ.get("ALLOWED_IMAGE_HOSTS", "").split(",") if h}
JOB_TTL_SECONDS = int(os.environ.get("JOB_TTL_SECONDS", str(24 * 3600)))
MAX_IMAGE_BYTES = 20 * 1024 * 1024
# Props: full shape model with 50 steps; octree 256 is plenty for objects a few percent of the map wide.
PROP_PARAMS = {"texture": True, "num_inference_steps": 50, "octree_resolution": 256, "face_count": 30000}
PROP_TIMEOUT_SECONDS = int(os.environ.get("PROP_TIMEOUT_SECONDS", str(4 * 3600)))
STAGES = ["Estimating depth", "Finding objects", "Building terrain", "Generating props", "Composing scene"]


class JobIn(BaseModel):
    image_url: str
    seed: int = 0


@dataclass
class Job:
    id: str
    params: JobIn
    status: str = "queued"
    stage: Optional[str] = None
    error: Optional[str] = None
    created: float = field(default_factory=time.time)
    progress: int = 0
    props_done: int = 0
    props_total: int = 0
    timings: dict = field(default_factory=dict)
    stats: dict = field(default_factory=dict)

    @property
    def dir(self):
        return os.path.join(DATA_DIR, self.id)


jobs: dict[str, Job] = {}
jobs_lock = threading.Lock()
work: "queue.Queue[str]" = queue.Queue(maxsize=20)


def fetch_image(url: str) -> Image.Image:
    u = urlparse(url)
    if u.scheme not in ("http", "https") or not u.hostname:
        raise ValueError("invalid url")
    if ALLOWED_IMAGE_HOSTS and u.hostname not in ALLOWED_IMAGE_HOSTS:
        raise ValueError("host not allowed")
    for info in socket.getaddrinfo(u.hostname, None):  # SSRF guard, as in the Hunyuan3D worker
        ip = ipaddress.ip_address(info[4][0])
        if (ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved) and not ALLOWED_IMAGE_HOSTS:
            raise ValueError("host resolves to a private address")
    with requests.get(url, stream=True, timeout=30) as r:
        r.raise_for_status()
        buf = BytesIO()
        for chunk in r.iter_content(64 * 1024):
            buf.write(chunk)
            if buf.tell() > MAX_IMAGE_BYTES:
                raise ValueError("file too large")
    img = Image.open(buf)
    img.load()
    return img


def generate_props(job: Job, crops: dict[str, Image.Image]) -> dict[str, bytes]:
    """Submit every variant to the Hunyuan3D worker (its queue runs them one by one), collect the GLBs."""
    auth = {"Authorization": f"Bearer {HUNYUAN_TOKEN}"}
    crop_dir = os.path.join(job.dir, "crops")
    os.makedirs(crop_dir, exist_ok=True)
    ids = {}
    for name, im in crops.items():
        im.save(os.path.join(crop_dir, f"{name}.png"))
        body = {"image_url": f"{PUBLIC_URL}/v1/crops/{job.id}/{name}.png", "seed": job.params.seed, **PROP_PARAMS}
        r = requests.post(f"{HUNYUAN_URL}/v1/jobs", json=body, headers=auth, timeout=30)
        r.raise_for_status()
        ids[name] = r.json()["id"]
    job.props_total = len(ids)
    out, deadline = {}, time.time() + PROP_TIMEOUT_SECONDS
    while len(out) < len(ids):
        if time.time() > deadline:
            raise RuntimeError("prop generation timed out")
        for name, jid in ids.items():
            if name in out:
                continue
            s = requests.get(f"{HUNYUAN_URL}/v1/jobs/{jid}", headers=auth, timeout=30)
            if s.status_code == 404:
                out[name] = b""  # worker restarted: this variant is skipped
                continue
            st = s.json()
            if st["status"] == "completed":
                m = requests.get(f"{HUNYUAN_URL}/v1/jobs/{jid}/model", headers=auth, timeout=120)
                out[name] = m.content if m.ok else b""
                with open(os.path.join(crop_dir, f"{name}.glb"), "wb") as f:  # kept with the crop for debugging
                    f.write(out[name])
            elif st["status"] == "failed":
                log.warning("prop %s failed: %s", name, st.get("error"))
                out[name] = b""
        job.props_done = len(out)
        time.sleep(5)
    return out


def progress(job: Job) -> int:
    if job.status == "completed":
        return 100
    if job.stage not in STAGES:
        return 0
    # Props dominate the run time: give them 80% of the bar.
    weights = {"Estimating depth": 5, "Finding objects": 10, "Building terrain": 3, "Generating props": 80, "Composing scene": 2}
    done = sum(weights[s] for s in STAGES[: STAGES.index(job.stage)])
    if job.stage == "Generating props" and job.props_total:
        done += weights["Generating props"] * job.props_done / job.props_total
    return min(99, int(done))


def run(job: Job):
    os.makedirs(job.dir, exist_ok=True)
    t0 = last = time.time()

    def on_stage(s: str):
        nonlocal last
        if job.stage:
            job.timings[job.stage] = round(time.time() - last, 1)
        job.stage, last = s, time.time()

    image = fetch_image(job.params.image_url)
    glb, stats = mapgen.run(image, DEVICE, lambda crops: generate_props(job, crops), on_stage)
    on_stage("done")
    job.timings["total"] = round(time.time() - t0, 1)
    with open(os.path.join(job.dir, "map.glb"), "wb") as f:
        f.write(glb)
    job.stats = stats


def gpu_loop():
    while True:
        job = jobs.get(work.get())
        if not job:
            continue
        job.status = "running"
        try:
            run(job)
            job.status = "completed"
        except Exception as e:
            log.error("job %s failed: %s", job.id, traceback.format_exc())
            job.status, job.error = "failed", str(e)[:500]
        finally:
            job.stage = None
            mapgen.free_memory()


def cleanup_loop():
    while True:
        time.sleep(600)
        cutoff = time.time() - JOB_TTL_SECONDS
        with jobs_lock:
            for j in [j for j in jobs.values() if j.created < cutoff and j.status in ("completed", "failed")]:
                jobs.pop(j.id, None)
                shutil.rmtree(j.dir, ignore_errors=True)


app = FastAPI(title="Map worker", docs_url=None, redoc_url=None)


def auth(authorization: str = Header(default="")):
    if not hmac.compare_digest(authorization.encode(), f"Bearer {TOKEN}".encode()):
        raise HTTPException(401, "unauthorized")


def get_job(job_id: str) -> Job:
    job = jobs.get(job_id)
    if not job:
        raise HTTPException(404, "job not found")
    return job


def status(job: Job) -> dict:
    pos = list(work.queue).index(job.id) if job.status == "queued" and job.id in work.queue else 0
    return {"id": job.id, "status": job.status, "stage": job.stage, "progress": progress(job), "queue_position": pos,
            "error": job.error, "timings": job.timings, "stats": job.stats,
            "props": {"done": job.props_done, "total": job.props_total}}


@app.get("/healthz")
def healthz():
    return {"ok": True, "device": DEVICE, "queued": work.qsize()}


@app.post("/v1/jobs", dependencies=[Depends(auth)], status_code=201)
def create_job(body: JobIn):
    job = Job(id=uuid.uuid4().hex, params=body)
    with jobs_lock:
        jobs[job.id] = job
    try:
        work.put_nowait(job.id)
    except queue.Full:
        jobs.pop(job.id, None)
        raise HTTPException(503, "queue full")
    return status(job)


@app.get("/v1/jobs/{job_id}", dependencies=[Depends(auth)])
def get_status(job_id: str):
    return status(get_job(job_id))


@app.get("/v1/jobs/{job_id}/model", dependencies=[Depends(auth)])
def get_model(job_id: str):
    job = get_job(job_id)
    path = os.path.join(job.dir, "map.glb")
    if job.status != "completed" or not os.path.exists(path):
        raise HTTPException(409, "not ready")
    return FileResponse(path, media_type="model/gltf-binary")


@app.get("/v1/crops/{job_id}/{name}.png")
def get_crop(job_id: str, name: str):
    if not re.fullmatch(r"[0-9a-f]{32}", job_id) or not re.fullmatch(r"[a-z]+_\d+", name):
        raise HTTPException(404)
    path = os.path.join(get_job(job_id).dir, "crops", f"{name}.png")
    if not os.path.exists(path):
        raise HTTPException(404)
    return FileResponse(path, media_type="image/png")


if __name__ == "__main__":
    os.makedirs(DATA_DIR, exist_ok=True)
    threading.Thread(target=gpu_loop, daemon=True).start()
    threading.Thread(target=cleanup_loop, daemon=True).start()
    log.info("map worker on %s, device %s, props via %s", PORT, DEVICE, HUNYUAN_URL)
    uvicorn.run(app, host=os.environ.get("HOST", "127.0.0.1"), port=PORT, log_level="warning")
