#!/usr/bin/env bash
# Sets up the map worker (game map image -> layered 3D scene) in worker/map/.venv. Mac (MPS) or CUDA.
# Requires uv (https://docs.astral.sh/uv/). Props are generated by the Hunyuan3D-2.1 worker (worker/*/setup.sh).
set -euo pipefail
cd "$(dirname "$0")"
MOGE_REV=74fbce054ebed49800de42d0ad0e83495065719a  # tested revision

[ -x .venv/bin/python ] || uv venv --python 3.12 .venv
uv pip install --python .venv/bin/python -r requirements.txt
[ -d MoGe/.git ] || git clone -q https://github.com/microsoft/MoGe.git MoGe
git -C MoGe fetch -q origin "$MOGE_REV" && git -C MoGe checkout -q FETCH_HEAD
uv pip install --python .venv/bin/python --no-deps -e MoGe
if command -v nvidia-smi >/dev/null && nvidia-smi -L 2>/dev/null | grep -q '^GPU'; then
  # MoGe-3 refiner (sparse 3D UNet) runs only on CUDA.
  uv pip install --python .venv/bin/python "flex-gemm @ git+https://github.com/JeffreyXiang/FlexGEMM.git@b2fadb29d41846c7981ade6801ffc689fae119cf"
fi
.venv/bin/python -c "import torch, moge, transformers; print('torch', torch.__version__, '| mps', torch.backends.mps.is_available(), '| cuda', torch.cuda.is_available())"
